version: '3'

services:

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - db

  backend:
    build:
     context: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - db

networks:
  db:
    driver: bridge
